=== microbiomedata/external-metadata-awareness/schema-ncbi_metadata_20250919-biosamples-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "access",
    "accession",
    "Attributes",
    "Description",
    "id",
    "Ids",
    "last_update",
    "Models",
    "Owner",
    "Package",
    "publication_date",
    "Status",
    "submission_date"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "access": {
      "type": "string"
    },
    "accession": {
      "type": "string"
    },
    "Attributes": {
      "type": "object",
      "required": [],
      "properties": {
        "Attribute": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "attribute_name"
            ],
            "properties": {
              "attribute_name": {
                "type": "string"
              },
              "content": {
                "type": "string"
              },
              "display_name": {
                "type": "string"
              },
              "harmonized_name": {
                "type": "string"
              },
              "unit": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "Description": {
      "type": "object",
      "required": [
        "Organism",
        "Title"
      ],
      "properties": {
        "Comment": {
          "type": "object",
          "required": [],
          "properties": {
            "Paragraph": {
              "anyOf": [
                {
                  "type": "object",
                  "required": [
                    "content"
                  ],
                  "properties": {
                    "content": {
                      "type": "string"
                    }
                  }
                },
                {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "required": [
                      "content"
                    ],
                    "properties": {
                      "content": {
                        "type": "string"
                      }
                    }
                  }
                }
              ]
            },
            "Table": {
              "type": "object",
              "required": [
                "Body",
                "Caption",
                "Header"
              ],
              "properties": {
                "Body": {
                  "type": "object",
                  "required": [
                    "Row"
                  ],
                  "properties": {
                    "Row": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "Cell"
                        ],
                        "properties": {
                          "Cell": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "required": [
                                "content"
                              ],
                              "properties": {
                                "content": {
                                  "type": "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "Caption": {
                  "type": "object",
                  "required": [
                    "content"
                  ],
                  "properties": {
                    "content": {
                      "type": "string"
                    }
                  }
                },
                "class": {
                  "type": "string"
                },
                "Header": {
                  "type": "object",
                  "required": [
                    "Cell"
                  ],
                  "properties": {
                    "Cell": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "content"
                        ],
                        "properties": {
                          "content": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "Organism": {
          "type": "object",
          "required": [
            "taxonomy_id",
            "taxonomy_name"
          ],
          "properties": {
            "OrganismName": {
              "type": "object",
              "required": [
                "content"
              ],
              "properties": {
                "content": {
                  "type": "string"
                }
              }
            },
            "taxonomy_id": {
              "type": "string"
            },
            "taxonomy_name": {
              "type": "string"
            }
          }
        },
        "Synonym": {
          "type": "object",
          "required": [
            "content",
            "db"
          ],
          "properties": {
            "content": {
              "type": "string"
            },
            "db": {
              "type": "string"
            }
          }
        },
        "Title": {
          "type": "object",
          "required": [
            "content"
          ],
          "properties": {
            "content": {
              "type": "string"
            }
          }
        }
      }
    },
    "id": {
      "type": "string"
    },
    "Ids": {
      "type": "object",
      "required": [
        "Id"
      ],
      "properties": {
        "Id": {
          "anyOf": [
            {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "content"
                ],
                "properties": {
                  "content": {
                    "type": "string"
                  },
                  "db": {
                    "type": "string"
                  },
                  "db_label": {
                    "type": "string"
                  },
                  "is_hidden": {
                    "type": "string"
                  },
                  "is_primary": {
                    "type": "string"
                  }
                }
              }
            },
            {
              "type": "object",
              "required": [
                "content",
                "db",
                "is_primary"
              ],
              "properties": {
                "content": {
                  "type": "string"
                },
                "db": {
                  "type": "string"
                },
                "is_primary": {
                  "type": "string"
                }
              }
            }
          ]
        }
      }
    },
    "last_update": {
      "type": "string"
    },
    "Links": {
      "type": "object",
      "required": [],
      "properties": {
        "Link": {
          "anyOf": [
            {
              "type": "object",
              "required": [
                "content",
                "label",
                "type"
              ],
              "properties": {
                "content": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "target": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              }
            },
            {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "content",
                  "label",
                  "type"
                ],
                "properties": {
                  "content": {
                    "type": "string"
                  },
                  "label": {
                    "type": "string"
                  },
                  "target": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        }
      }
    },
    "Models": {
      "type": "object",
      "required": [
        "Model"
      ],
      "properties": {
        "Model": {
          "anyOf": [
            {
              "type": "object",
              "required": [
                "content"
              ],
              "properties": {
                "content": {
                  "type": "string"
                },
                "version": {
                  "type": "string"
                }
              }
            },
            {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "content"
                ],
                "properties": {
                  "content": {
                    "type": "string"
                  },
                  "version": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        }
      }
    },
    "Owner": {
      "type": "object",
      "required": [
        "Name"
      ],
      "properties": {
        "Contacts": {
          "type": "object",
          "required": [
            "Contact"
          ],
          "properties": {
            "Contact": {
              "type": "object",
              "required": [],
              "properties": {
                "Address": {
                  "type": "object",
                  "required": [
                    "Street"
                  ],
                  "properties": {
                    "Street": {
                      "type": "object",
                      "required": [
                        "content"
                      ],
                      "properties": {
                        "content": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "fax": {
                  "type": "string"
                },
                "lab": {
                  "type": "string"
                },
                "Name": {
                  "type": "object",
                  "required": [
                    "Last"
                  ],
                  "properties": {
                    "First": {
                      "type": "object",
                      "required": [
                        "content"
                      ],
                      "properties": {
                        "content": {
                          "type": "string"
                        }
                      }
                    },
                    "Last": {
                      "type": "object",
                      "required": [
                        "content"
                      ],
                      "properties": {
                        "content": {
                          "type": "string"
                        }
                      }
                    },
                    "Middle": {
                      "type": "object",
                      "required": [
                        "content"
                      ],
                      "properties": {
                        "content": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "Name": {
          "type": "object",
          "required": [],
          "properties": {
            "abbreviation": {
              "type": "string"
            },
            "content": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        }
      }
    },
    "Package": {
      "type": "object",
      "required": [
        "content",
        "display_name"
      ],
      "properties": {
        "content": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        }
      }
    },
    "publication_date": {
      "type": "string"
    },
    "Status": {
      "type": "object",
      "required": [
        "status",
        "when"
      ],
      "properties": {
        "status": {
          "type": "string"
        },
        "when": {
          "type": "string"
        }
      }
    },
    "submission_date": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== microbiomedata/external-metadata-awareness/notebooks/studies_exploration/emp_500_ng/misc/MacRae-Crerar_ncbi_metadata.biosamples.json
[{
  "_id": {
    "$oid": "677f49bc0a6241ac79631e6d"
  },
  "access": "public",
  "publication_date": "2020-12-17T00:00:00.000",
  "last_update": "2021-08-23T00:27:30.000",
  "submission_date": "2020-12-19T08:06:11.113",
  "id": "17119136",
  "accession": "SAMEA7724107",
  "Ids": {
    "Id": [
      {
        "content": "SAMEA7724107",
        "db": "BioSample",
        "is_primary": "1"
      },
      {
        "content": "ERS5471484",
        "db": "SRA"
      }
    ]
  },
  "Description": {
    "Title": {
      "content": "13114.macrae.crerar.3.s001"
    },
    "Organism": {
      "taxonomy_id": "410658",
      "taxonomy_name": "soil metagenome",
      "OrganismName": {
        "content": "soil metagenome"
      }
    },
    "Comment": {
      "Paragraph": {
        "content": "Northern Mongolian soil 454"
      }
    }
  },
  "Owner": {
    "Name": {
      "content": "EBI"
    }
  },
  "Models": {
    "Model": {
      "content": "Generic"
    }
  },
  "Package": {
    "content": "Generic.1.0",
    "display_name": "Generic"
  },
  "Attributes": {
    "Attribute": [
      {
        "content": "2020-12-17",
        "attribute_name": "ENA first public"
      },
      {
        "content": "2020-12-16",
        "attribute_name": "ENA last update"
      },
      {
        "content": "ERC000011",
        "attribute_name": "ENA-CHECKLIST"
      },
      {
        "content": "SAMEA7724107",
        "attribute_name": "External Id"
      },
      {
        "content": "UCSDMI",
        "attribute_name": "INSDC center alias"
      },
      {
        "content": "University of California San Diego Microbiome Initiative",
        "attribute_name": "INSDC center name"
      },
      {
        "content": "2020-12-17T04:08:06Z",
        "attribute_name": "INSDC first public"
      },
      {
        "content": "2020-12-16T01:23:54Z",
        "attribute_name": "INSDC last update"
      },
      {
        "content": "public",
        "attribute_name": "INSDC status"
      },
      {
        "content": "qiita_sid_13114:13114.macrae.crerar.3.s001",
        "attribute_name": "Submitter Id"
      },
      {
        "content": "27.8",
        "attribute_name": "air_temp",
        "harmonized_name": "air_temp",
        "display_name": "air temperature"
      },
      {
        "content": "353.0",
        "attribute_name": "alpha_shotgun_woltka_rar3450_richness"
      },
      {
        "content": "B09",
        "attribute_name": "block"
      },
      {
        "content": "7/9/12 15:12",
        "attribute_name": "collection_timestamp"
      },
      {
        "content": "montaine steppe",
        "attribute_name": "cur_vegetation",
        "harmonized_name": "cur_vegetation",
        "display_name": "current vegetation"
      },
      {
        "content": "0.05",
        "attribute_name": "depth_sample"
      },
      {
        "content": "well drained",
        "attribute_name": "drainage_class",
        "harmonized_name": "drainage_class",
        "display_name": "drainage classification"
      },
      {
        "content": "1741",
        "attribute_name": "elevation",
        "harmonized_name": "elev",
        "display_name": "elevation"
      },
      {
        "content": "MacRae-Crerar",
        "attribute_name": "emp500_principal_investigator"
      },
      {
        "content": "3",
        "attribute_name": "emp500_study_id"
      },
      {
        "content": "Mongolia soils (NSF PIRE)",
        "attribute_name": "emp500_title"
      },
      {
        "content": "Non-saline",
        "attribute_name": "empo_2"
      },
      {
        "content": "Soil (non-saline)",
        "attribute_name": "empo_3"
      },
      {
        "content": "montane grasslands and shrubland biome",
        "attribute_name": "env biome",
        "harmonized_name": "env_broad_scale",
        "display_name": "broad-scale environmental context"
      },
      {
        "content": "steppe soil",
        "attribute_name": "env feature",
        "harmonized_name": "env_local_scale",
        "display_name": "local-scale environmental context"
      },
      {
        "content": "soil",
        "attribute_name": "env package",
        "harmonized_name": "env_package",
        "display_name": "environmental package"
      },
      {
        "content": "soil",
        "attribute_name": "env_material",
        "harmonized_name": "env_medium",
        "display_name": "environmental medium"
      },
      {
        "content": "soil",
        "attribute_name": "environmental_package",
        "harmonized_name": "env_package",
        "display_name": "environmental package"
      },
      {
        "content": "EMP_McR3_1_008_GC",
        "attribute_name": "gcms_sample_name"
      },
      {
        "content": "Mongolia",
        "attribute_name": "geo loc name",
        "harmonized_name": "geo_loc_name",
        "display_name": "geographic location"
      },
      {
        "content": "51.01.658",
        "attribute_name": "latitude"
      },
      {
        "content": "8.00",
        "attribute_name": "lcms_batch"
      },
      {
        "content": "Bulk_Seed_PNNL",
        "attribute_name": "lcms_extraction_protocol"
      },
      {
        "content": "100.45.643",
        "attribute_name": "longitude"
      },
      {
        "content": "7.3",
        "attribute_name": "ph",
        "harmonized_name": "ph",
        "display_name": "pH"
      },
      {
        "content": "UCSD Knight Lab Freezer I and University of Pennsylvania",
        "attribute_name": "physical_specimen_location"
      },
      {
        "content": "NSF PIRE Mongolia Project",
        "attribute_name": "project name",
        "harmonized_name": "project_name",
        "display_name": "project name"
      },
      {
        "content": "51.6",
        "attribute_name": "relative humidity"
      },
      {
        "content": "0.565",
        "attribute_name": "resp_ave"
      },
      {
        "content": "0.62",
        "attribute_name": "respiration1"
      },
      {
        "content": "0.51",
        "attribute_name": "respiration2"
      },
      {
        "content": "qiita_sid_13114:13114.macrae.crerar.3.s001",
        "attribute_name": "sample name",
        "harmonized_name": "sample_name",
        "display_name": "sample name"
      },
      {
        "content": "soil",
        "attribute_name": "sample type",
        "harmonized_name": "sample_type",
        "display_name": "sample type"
      },
      {
        "content": "bulk",
        "attribute_name": "sampling method"
      },
      {
        "content": "11.4",
        "attribute_name": "soil_moisture1"
      },
      {
        "content": "11.5",
        "attribute_name": "soil_moisture2"
      },
      {
        "content": "13.9",
        "attribute_name": "soil_moisture3"
      },
      {
        "content": "12.26666667",
        "attribute_name": "soil_moisture_ave"
      },
      {
        "content": "74",
        "attribute_name": "soil_salinity1"
      },
      {
        "content": "76",
        "attribute_name": "soil_salinity2"
      },
      {
        "content": "65",
        "attribute_name": "soil_salinity3"
      },
      {
        "content": "71.66666667",
        "attribute_name": "soil_salinity_ave"
      },
      {
        "content": "27.4",
        "attribute_name": "soil_temp1"
      },
      {
        "content": "31.2",
        "attribute_name": "soil_temp2"
      },
      {
        "content": "30.4",
        "attribute_name": "soil_temp3"
      },
      {
        "content": "29.66666667",
        "attribute_name": "soil_temp_ave"
      },
      {
        "content": "1",
        "attribute_name": "study_sample_number"
      }
    ]
  },
  "Status": {
    "status": "live",
    "when": "2020-12-20T10:30:11.242"
  }
},
{
  "_id": {
    "$oid": "677f49bc0a6241ac79631e6e"
  },
  "access": "public",
  "publication_date": "2020-12-17T00:00:00.000",
  "last_update": "2021-08-23T00:27:30.000",
  "submission_date": "2020-12-19T08:06:11.176",
  "id": "17119137",
  "accession": "SAMEA7724108",
  "Ids": {
    "Id": [
      {
        "content": "SAMEA7724108",
        "db": "BioSample",
        "is_primary": "1"
      },
      {
        "content": "ERS5471485",
        "db": "SRA"
      }
    ]
  },
  "Description": {
    "Title": {
      "content": "13114.macrae.crerar.3.s002"
    },
    "Organism": {
      "taxonomy_id": "410658",
      "taxonomy_name": "soil metagenome",
      "OrganismName": {
        "content": "soil metagenome"
      }
    },
    "Comment": {
      "Paragraph": {
        "content": "Northern Mongolian soil 455"
      }
    }
  },
  "Owner": {
    "Name": {
      "content": "EBI"
    }
  },
  "Models": {
    "Model": {
      "content": "Generic"
    }
  },
  "Package": {
    "content": "Generic.1.0",
    "display_name": "Generic"
  },
  "Attributes": {
    "Attribute": [
      {
        "content": "2020-12-17",
        "attribute_name": "ENA first public"
      },
      {
        "content": "2020-12-16",
        "attribute_name": "ENA last update"
      },
      {
        "content": "ERC000011",
        "attribute_name": "ENA-CHECKLIST"
      },
      {
        "content": "SAMEA7724108",
        "attribute_name": "External Id"
      },
      {
        "content": "UCSDMI",
        "attribute_name": "INSDC center alias"
      },
      {
        "content": "University of California San Diego Microbiome Initiative",
        "attribute_name": "INSDC center name"
      },
      {
        "content": "2020-12-17T04:08:06Z",
        "attribute_name": "INSDC first public"
      },
      {
        "content": "2020-12-16T01:23:54Z",
        "attribute_name": "INSDC last update"
      },
      {
        "content": "public",
        "attribute_name": "INSDC status"
      },
      {
        "content": "qiita_sid_13114:13114.macrae.crerar.3.s002",
        "attribute_name": "Submitter Id"
      },
      {
        "content": "24.9",
        "attribute_name": "air_temp",
        "harmonized_name": "air_temp",
